# This should be a dictionary at the top level, not a list
models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo

rails:
  input:
    flows:
      - self check input
  output:
    flows:
      - self check output